from .sys_config import SysConfigMapper
from .sys_dept import SysDeptMapper
from .sys_dict_data import SysDictDataMapper
from .sys_dict_type import SysDictTypeMapper
from .sys_logininfor import SysLogininforMapper
from .sys_menu import SysMenuMapper
from .sys_notice import SysNoticeMapper
from .sys_oper_log import SysOperLogMapper
from .sys_post import SysPostMapper
from .sys_role_dept import SysRoleDeptMapper
from .sys_role_menu import SysRoleMenuMapper
from .sys_role import SysRoleMapper
from .sys_user import SysUserMapper
from .sys_user_post import SysUserPostMapper
from .sys_user_role import SysUserRoleMapper
