"""增加活动预约表

Revision ID: 227d75fbd92a
Revises: 7b1a75ca099f
Create Date: 2026-01-29 11:13:03.947419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '227d75fbd92a'
down_revision: Union[str, Sequence[str], None] = '7b1a75ca099f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exb_activity_reservation',
    sa.Column('reservation_id', sa.BigInteger(), autoincrement=True, nullable=False, comment='预约ID'),
    sa.Column('activity_id', sa.BigInteger(), nullable=False, comment='活动ID'),
    sa.Column('wx_user_id', sa.BigInteger(), nullable=False, comment='微信用户ID'),
    sa.Column('registration_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='报名时间'),
    sa.Column('phone_number', sa.String(length=20), nullable=True, comment='手机号码'),
    sa.Column('del_flag', mysql.TINYINT(), server_default=sa.text("'0'"), nullable=False, comment='删除标志（0存在 1删除）'),
    sa.Column('create_by', sa.String(length=64), nullable=True, comment='创建者'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('update_by', sa.String(length=64), nullable=True, comment='更新者'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.Column('remark', sa.String(length=500), nullable=True, comment='备注'),
    sa.PrimaryKeyConstraint('reservation_id'),
    sa.UniqueConstraint('activity_id', 'wx_user_id', name='uk_activityid_wxuserid'),
    comment='活动预约表'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exb_activity_reservation')
    # ### end Alembic commands ###
