"""新增博物馆对象

Revision ID: 28c4bdcbbcaa
Revises: e95d08d52474
Create Date: 2025-12-27 14:40:34.604088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision: str = '28c4bdcbbcaa'
down_revision: Union[str, Sequence[str], None] = 'e95d08d52474'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 判断数据库里表是否存在
    inspector = inspect(op.get_bind())
    if not inspector.has_table("exb_museum"):
        op.create_table('exb_museum',
        sa.Column('museum_id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False, comment='博物馆ID'),
        sa.Column('museum_name', mysql.VARCHAR(length=200), nullable=False, comment='博物馆名称'),
        sa.Column('address', mysql.VARCHAR(length=500), nullable=True, comment='博物馆地址'),
        sa.Column('description', mysql.TEXT(), nullable=True, comment='博物馆简介'),
        sa.Column('status', mysql.TINYINT(), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='状态（0正常 1停用）'),
        sa.Column('del_flag', mysql.TINYINT(), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='删除标志（0存在 1删除）'),
        sa.Column('create_by', mysql.VARCHAR(length=64), nullable=True, comment='创建者'),
        sa.Column('create_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
        sa.Column('update_by', mysql.VARCHAR(length=64), nullable=True, comment='更新者'),
        sa.Column('update_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
        sa.Column('remark', mysql.VARCHAR(length=500), nullable=True, comment='备注'),
        sa.PrimaryKeyConstraint('museum_id'),
        comment='博物馆信息表',
        mysql_collate='utf8mb4_0900_ai_ci',
        mysql_comment='博物馆信息表',
        mysql_default_charset='utf8mb4',
        mysql_engine='InnoDB'
        )
    
    if not inspector.has_table("exb_museum_media"):
        op.create_table('exb_museum_media',
        sa.Column('media_id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False, comment='多媒体ID'),
        sa.Column('museum_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False, comment='博物馆ID'),
        sa.Column('media_name', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=False, comment='媒体名称'),
        sa.Column('media_type', mysql.TINYINT(), autoincrement=False, nullable=False, comment='媒体类型（1图片 2视频 3音频）'),
        sa.Column('media_url', mysql.VARCHAR(length=500), nullable=False, comment='媒体URL'),
        sa.Column('cover_url', mysql.VARCHAR(length=500), nullable=True, comment='封面图（视频封面/音频封面）'),
        sa.Column('size', mysql.INTEGER(), autoincrement=False, nullable=True, comment='文件大小'),
        sa.Column('duration', mysql.INTEGER(), autoincrement=False, nullable=True, comment='时长（秒，视频/音频）'),
        sa.Column('sort', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='排序号（越小越靠前）'),
        sa.Column('is_cover', mysql.TINYINT(), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='是否封面（0否 1是）'),
        sa.Column('status', mysql.TINYINT(), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='状态（0正常 1停用）'),
        sa.Column('del_flag', mysql.TINYINT(), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='删除标志（0存在 1删除）'),
        sa.Column('create_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
        sa.Column('update_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
        sa.ForeignKeyConstraint(['museum_id'], ['exb_museum.museum_id'], name=op.f('fk_museum_media')),
        sa.PrimaryKeyConstraint('media_id'),
        comment='博物馆多媒体表',
        mysql_collate='utf8mb4_0900_ai_ci',
        mysql_comment='博物馆多媒体表',
        mysql_default_charset='utf8mb4',
        mysql_engine='InnoDB'
        )
        op.create_index(op.f('idx_museum_media_type'), 'exb_museum_media', ['museum_id', 'media_type'], unique=False)
        op.create_index(op.f('idx_museum_id'), 'exb_museum_media', ['museum_id'], unique=False)

    op.create_unique_constraint('uniq_job_name_group', 'sys_job', ['job_name', 'job_group'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    inspector = inspect(op.get_bind())
    if inspector.has_table("exb_museum_media"):
        op.drop_table('exb_museum')
        op.drop_index(op.f('idx_museum_id'), table_name='exb_museum_media')
        op.drop_index(op.f('idx_museum_media_type'), table_name='exb_museum_media')
    if inspector.has_table("exb_museum_media"):
        op.drop_table('exb_museum_media')

    op.drop_constraint('uniq_job_name_group', 'sys_job', type_='unique')
    # ### end Alembic commands ###
