"""增加展厅、展览单元等对象

Revision ID: 51b14f98e86b
Revises: eff0c91d6ac9
Create Date: 2026-01-12 09:12:58.146644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '51b14f98e86b'
down_revision: Union[str, Sequence[str], None] = 'eff0c91d6ac9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exb_exhibition_unit',
    sa.Column('unit_id', sa.BigInteger(), autoincrement=True, nullable=False, comment='展览单元ID'),
    sa.Column('unit_name', sa.String(length=500), nullable=False, comment='单元名称'),
    sa.Column('exhibition_id', sa.BigInteger(), nullable=False, comment='所属展览ID'),
    sa.Column('exhibit_label', sa.Text(), nullable=True, comment='展签'),
    sa.Column('guide_text', sa.Text(), nullable=True, comment='导览词'),
    sa.Column('unit_type', mysql.TINYINT(), nullable=False, comment='类型(0展品单元 1文字单元 2多媒体单元)'),
    sa.Column('hall_id', sa.BigInteger(), nullable=True, comment='所在展厅ID'),
    sa.Column('section', sa.String(length=255), nullable=True, comment='所属章节'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='顺序'),
    sa.Column('collections', sa.JSON(), nullable=True, comment='关联藏品ID列表(JSON数组存储，仅展品单元类型使用)'),
    sa.Column('status', mysql.TINYINT(), server_default=sa.text("'0'"), nullable=False, comment='状态（0正常 1停用）'),
    sa.Column('del_flag', mysql.TINYINT(), server_default=sa.text("'0'"), nullable=False, comment='删除标志（0存在 1删除）'),
    sa.Column('create_by', sa.String(length=64), nullable=True, comment='创建者'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('update_by', sa.String(length=64), nullable=True, comment='更新者'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.Column('remark', sa.String(length=500), nullable=True, comment='备注'),
    sa.PrimaryKeyConstraint('unit_id'),
    comment='展览单元信息表'
    )
    op.create_table('exb_museum_hall',
    sa.Column('hall_id', sa.BigInteger(), autoincrement=True, nullable=False, comment='展厅ID'),
    sa.Column('hall_name', sa.String(length=200), nullable=False, comment='展厅名称'),
    sa.Column('location', sa.String(length=500), nullable=True, comment='位置'),
    sa.Column('museum_id', sa.BigInteger(), nullable=False, comment='所属博物馆ID'),
    sa.Column('status', mysql.TINYINT(), server_default=sa.text("'0'"), nullable=False, comment='状态（0正常 1停用）'),
    sa.Column('del_flag', mysql.TINYINT(), server_default=sa.text("'0'"), nullable=False, comment='删除标志（0存在 1删除）'),
    sa.Column('create_by', sa.String(length=64), nullable=True, comment='创建者'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('update_by', sa.String(length=64), nullable=True, comment='更新者'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.Column('remark', sa.String(length=500), nullable=True, comment='备注'),
    sa.PrimaryKeyConstraint('hall_id'),
    comment='展厅信息表'
    )
    op.add_column('exb_exhibition', sa.Column('sections', sa.JSON(), nullable=True, comment='展览章节（JSON数组存储）'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exb_exhibition', 'sections')
    op.drop_table('exb_museum_hall')
    op.drop_table('exb_exhibition_unit')
    # ### end Alembic commands ###
