"""sync all schema

Revision ID: 5d4de9884811
Revises: 773850cad82d
Create Date: 2026-01-06 20:54:44.384492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d4de9884811'
down_revision: Union[str, Sequence[str], None] = '773850cad82d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_museum_media'), 'exb_museum_media', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('fk_museum_media'), 'exb_museum_media', 'exb_museum', ['museum_id'], ['museum_id'])
    # ### end Alembic commands ###
