"""增加小程序的app_secret

Revision ID: 7bfe4290bd1d
Revises: 51b14f98e86b
Create Date: 2026-01-17 21:39:56.373117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7bfe4290bd1d'
down_revision: Union[str, Sequence[str], None] = '51b14f98e86b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exb_museum', sa.Column('app_secret', sa.String(length=100), nullable=True, comment='小程序AppSecret'))
    op.alter_column('exb_museum_media', 'object_type',
               existing_type=mysql.VARCHAR(length=50),
               comment='对象类型（museum, exhibition, collection, exhibition_unit等）',
               existing_comment='对象类型（museum, exhibition, collection等）',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exb_museum_media', 'object_type',
               existing_type=mysql.VARCHAR(length=50),
               comment='对象类型（museum, exhibition, collection等）',
               existing_comment='对象类型（museum, exhibition, collection, exhibition_unit等）',
               existing_nullable=False)
    op.drop_column('exb_museum', 'app_secret')
    # ### end Alembic commands ###
