"""增加展览和藏品

Revision ID: 7c2e504df7e5
Revises: 5d4de9884811
Create Date: 2026-01-07 16:01:47.539663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7c2e504df7e5'
down_revision: Union[str, Sequence[str], None] = '5d4de9884811'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exb_collection',
    sa.Column('collection_id', sa.BigInteger(), autoincrement=True, nullable=False, comment='藏品ID'),
    sa.Column('collection_name', sa.String(length=500), nullable=False, comment='藏品名'),
    sa.Column('collection_type', sa.String(length=50), nullable=False, comment='类型(油画、书法、瓷器等)'),
    sa.Column('size_info', sa.String(length=200), nullable=True, comment='尺寸'),
    sa.Column('material', sa.String(length=100), nullable=True, comment='材质'),
    sa.Column('age', sa.String(length=100), nullable=True, comment='年代'),
    sa.Column('author', sa.String(length=100), nullable=True, comment='作者'),
    sa.Column('description', sa.Text(), nullable=True, comment='藏品简介'),
    sa.Column('exhibition_id', sa.BigInteger(), nullable=True, comment='所属展览ID'),
    sa.Column('museum_id', sa.BigInteger(), nullable=False, comment='所属博物馆ID'),
    sa.Column('status', mysql.TINYINT(), server_default=sa.text("'0'"), nullable=False, comment='状态（0正常 1停用）'),
    sa.Column('del_flag', mysql.TINYINT(), server_default=sa.text("'0'"), nullable=False, comment='删除标志（0存在 1删除）'),
    sa.Column('create_by', sa.String(length=64), nullable=True, comment='创建者'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('update_by', sa.String(length=64), nullable=True, comment='更新者'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.Column('remark', sa.String(length=500), nullable=True, comment='备注'),
    sa.PrimaryKeyConstraint('collection_id'),
    comment='藏品信息表'
    )
    op.create_table('exb_exhibition',
    sa.Column('exhibition_id', sa.BigInteger(), autoincrement=True, nullable=False, comment='展览ID'),
    sa.Column('exhibition_name', sa.String(length=500), nullable=False, comment='展名'),
    sa.Column('description', sa.Text(), nullable=True, comment='展览简介'),
    sa.Column('museum_id', sa.BigInteger(), nullable=False, comment='所属博物馆ID'),
    sa.Column('hall', sa.String(length=100), nullable=True, comment='展厅'),
    sa.Column('start_time', sa.DateTime(), nullable=False, comment='展览开始时间'),
    sa.Column('end_time', sa.DateTime(), nullable=False, comment='展览结束时间'),
    sa.Column('organizer', sa.String(length=500), nullable=True, comment='主办单位'),
    sa.Column('exhibition_type', mysql.TINYINT(), server_default=sa.text("'0'"), nullable=False, comment='展览类型（0长期 1临时）'),
    sa.Column('content_tags', sa.String(length=500), nullable=True, comment='内容标签'),
    sa.Column('status', mysql.TINYINT(), server_default=sa.text("'0'"), nullable=False, comment='状态（0正常 1停用）'),
    sa.Column('del_flag', mysql.TINYINT(), server_default=sa.text("'0'"), nullable=False, comment='删除标志（0存在 1删除）'),
    sa.Column('create_by', sa.String(length=64), nullable=True, comment='创建者'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('update_by', sa.String(length=64), nullable=True, comment='更新者'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.Column('remark', sa.String(length=500), nullable=True, comment='备注'),
    sa.PrimaryKeyConstraint('exhibition_id'),
    comment='展览信息表'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exb_exhibition')
    op.drop_table('exb_collection')
    # ### end Alembic commands ###
