"""新增微信用户对象

Revision ID: 8ec3f36c22e8
Revises: 7bfe4290bd1d
Create Date: 2026-01-28 08:39:16.074892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8ec3f36c22e8'
down_revision: Union[str, Sequence[str], None] = '7bfe4290bd1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exb_wx_user',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('app_id', sa.String(length=64), nullable=False, comment='微信应用ID'),
    sa.Column('open_id', sa.String(length=64), nullable=False, comment='微信用户OpenID'),
    sa.Column('union_id', sa.String(length=64), nullable=True, comment='微信用户UnionID'),
    sa.Column('session_key', sa.String(length=128), nullable=True, comment='微信用户SessionKey'),
    sa.Column('avatar_url', sa.Text(), nullable=True, comment='头像URL'),
    sa.Column('nickname', sa.String(length=100), nullable=True, comment='昵称'),
    sa.Column('status', mysql.TINYINT(), server_default=sa.text("'0'"), nullable=False, comment='状态（0正常 1禁用）'),
    sa.Column('del_flag', mysql.TINYINT(), server_default=sa.text("'0'"), nullable=False, comment='删除标志（0存在 1删除）'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.Column('remark', sa.String(length=500), nullable=True, comment='备注'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_id', 'open_id', name='uk_appid_openid'),
    comment='微信用户表'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exb_wx_user')
    # ### end Alembic commands ###
