"""扩展媒体表

Revision ID: a332ce6684df
Revises: 057f04c42df5
Create Date: 2026-01-08 16:17:04.271165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision: str = 'a332ce6684df'
down_revision: Union[str, Sequence[str], None] = '057f04c42df5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exb_museum_media', sa.Column('object_type', sa.String(length=50), nullable=False, comment='对象类型（museum, exhibition, collection等）'))
    op.add_column('exb_museum_media', sa.Column('object_id', sa.BigInteger(), nullable=False, comment='关联对象ID'))

    # 迁移原museum_id的数据到 object_id，并设置 object_type 为 'museum'
    conn = op.get_bind()
    conn.execute(text("UPDATE exb_museum_media SET object_id = museum_id, object_type = 'museum'"))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exb_museum_media', 'object_id')
    op.drop_column('exb_museum_media', 'object_type')
    # ### end Alembic commands ###
