"""增加博物馆所属部分的字段

Revision ID: aa09f01c20aa
Revises: 5fba54304416
Create Date: 2026-02-02 10:03:24.615033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa09f01c20aa'
down_revision: Union[str, Sequence[str], None] = '5fba54304416'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exb_museum', sa.Column('dept_id', sa.BigInteger(), nullable=True, comment='所属部门ID'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exb_museum', 'dept_id')
    # ### end Alembic commands ###
