"""增加活动对象

Revision ID: d7e020d459ad
Revises: 8ec3f36c22e8
Create Date: 2026-01-28 11:27:15.365417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd7e020d459ad'
down_revision: Union[str, Sequence[str], None] = '8ec3f36c22e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exb_activity',
    sa.Column('activity_id', sa.BigInteger(), autoincrement=True, nullable=False, comment='活动ID'),
    sa.Column('activity_name', sa.String(length=255), nullable=False, comment='活动名称'),
    sa.Column('introduction', sa.Text(), nullable=True, comment='活动介绍'),
    sa.Column('activity_type', sa.String(length=100), nullable=False, comment='活动类型(讲座/表演/手工/其他等)'),
    sa.Column('target_audience', sa.String(length=255), server_default=sa.text("'不限'"), nullable=False, comment='活动对象'),
    sa.Column('location', sa.String(length=255), nullable=False, comment='活动地点'),
    sa.Column('activity_start_time', sa.DateTime(), nullable=False, comment='活动开始时间'),
    sa.Column('activity_end_time', sa.DateTime(), nullable=True, comment='活动结束时间'),
    sa.Column('registration_count', sa.Integer(), server_default=sa.text("'0'"), nullable=False, comment='报名人数'),
    sa.Column('max_registration', sa.Integer(), server_default=sa.text("'0'"), nullable=False, comment='最大报名人数'),
    sa.Column('presenter', sa.String(length=255), nullable=True, comment='主讲人或表演团队'),
    sa.Column('museum_id', sa.BigInteger(), nullable=True, comment='所属博物馆ID'),
    sa.Column('status', mysql.TINYINT(), server_default=sa.text("'0'"), nullable=False, comment='状态（0正常 1停用）'),
    sa.Column('del_flag', mysql.TINYINT(), server_default=sa.text("'0'"), nullable=False, comment='删除标志（0存在 1删除）'),
    sa.Column('create_by', sa.String(length=64), nullable=True, comment='创建者'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('update_by', sa.String(length=64), nullable=True, comment='更新者'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.Column('remark', sa.String(length=500), nullable=True, comment='备注'),
    sa.PrimaryKeyConstraint('activity_id'),
    comment='活动信息表'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exb_activity')
    # ### end Alembic commands ###
