"""删除媒体表的museum_id

Revision ID: eff0c91d6ac9
Revises: a332ce6684df
Create Date: 2026-01-09 11:32:14.161685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'eff0c91d6ac9'
down_revision: Union[str, Sequence[str], None] = 'a332ce6684df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_museum_id'), table_name='exb_museum_media')
    op.drop_index(op.f('idx_museum_media_type'), table_name='exb_museum_media')
    op.create_index('idx_object_type_id', 'exb_museum_media', ['object_type', 'object_id'], unique=False)
    op.drop_column('exb_museum_media', 'museum_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exb_museum_media', sa.Column('museum_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False, comment='博物馆ID'))
    op.drop_index('idx_object_type_id', table_name='exb_museum_media')
    op.create_index(op.f('idx_museum_media_type'), 'exb_museum_media', ['museum_id', 'media_type'], unique=False)
    op.create_index(op.f('idx_museum_id'), 'exb_museum_media', ['museum_id'], unique=False)
    # ### end Alembic commands ###