from .sys_config import SysConfigService
from .sys_dept import SysDeptService
from .sys_dict_data import SysDictDataService
from .sys_dict_type import SysDictTypeService
from .sys_logininfo import SysLogininforService
from .sys_menu import SysMenuService
from .sys_notice import SysNoticeService
from .sys_oper_log import SysOperLogService
from .sys_post import SysPostService
from .sys_role import SysRoleService
from .sys_user_online import SysUserOnlineService
from .sys_user import SysUserService